name: CI
permissions: 
  actions: read
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Install dependencies
      run: pip install -r requirements.txt
  
  deploy:
    needs: build
    concurrency: 
      group: production-deploy
      cancel-in-progress: false
    runs-on: ubuntu-latest
    steps:
    - name: Display Hello World
      run: |
            echo "Welcome to GitHub Actions" 
            sleep 300s