# 
name: Matrix configuration
on: 
  push: 
  workflow_dispatch: 
jobs:
  deploy:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-20.04, ubuntu-18.04, windows-latest,windows-2019 ]
        images: [hello-world, alpine]
        exclude:
          - images: alpine
            os: [windows-latest, windows-2019]
        include:
          - images: amd64/alpine
            os: ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Docker Detail 
        run: docker info
      - name: Run image on
        run: docker run ${{ matrix.images }}