# 
name: Matrix configuration
on: 
  push: 
  workflow_dispatch: 
jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Docker info
        run: docker info
      - name: Docker hello world
        run: docker run hello-world

  windows:
    runs-on: windows-latest
    steps:
      - name: Docker info
        run: docker info
      - name: Docker hello world
        run: docker run hello-world